#!/bin/sh

make &&

(cd tests; ./testallmeta) &&

# Check that using the *new* compiler to compile itself
# produces the same VM-assembly code. It's OK for this check
# to fail, if you expect a nonessential or desired difference,
# but you should stop and think whether you do.
./elv selvc.elv <selvc.scm >selvc2.s &&
diff -u newselvc.s selvc2.s &&

mv newselvc.elv selvc.elv
